/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CompetitionsCompetitionIdRouteImport } from './routes/competitions_.$competitionId'
import { Route as FixturesFixtureIdRouteImport } from './routes/fixtures.$fixtureId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players_.$playerId'
import { Route as TeamsTeamIdRouteImport } from './routes/teams_.$teamId'
import { Route as VenuesVenueIdRouteImport } from './routes/venues_.$venueId'
import { Route as FixturesFixtureIdLineupsRouteImport } from './routes/fixtures.$fixtureId_.lineups'
import { Route as FixturesFixtureIdOddsRouteImport } from './routes/fixtures.$fixtureId_.odds'
import { Route as FixturesFixtureIdStatsRouteImport } from './routes/fixtures.$fixtureId_.stats'
import { Route as FixturesFixtureIdTimelineRouteImport } from './routes/fixtures.$fixtureId_.timeline'
import { Route as TeamsTeamIdSquadRouteImport } from './routes/teams_.$teamId_.squad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsCompetitionIdRoute =
  CompetitionsCompetitionIdRouteImport.update({
    id: '/competitions_/$competitionId',
    path: '/competitions/$competitionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FixturesFixtureIdRoute = FixturesFixtureIdRouteImport.update({
  id: '/fixtures/$fixtureId',
  path: '/fixtures/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players_/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams_/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/venues_/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesFixtureIdLineupsRoute =
  FixturesFixtureIdLineupsRouteImport.update({
    id: '/fixtures/$fixtureId_/lineups',
    path: '/fixtures/$fixtureId/lineups',
    getParentRoute: () => rootRouteImport,
  } as any)
const FixturesFixtureIdOddsRoute = FixturesFixtureIdOddsRouteImport.update({
  id: '/fixtures/$fixtureId_/odds',
  path: '/fixtures/$fixtureId/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesFixtureIdStatsRoute = FixturesFixtureIdStatsRouteImport.update({
  id: '/fixtures/$fixtureId_/stats',
  path: '/fixtures/$fixtureId/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesFixtureIdTimelineRoute =
  FixturesFixtureIdTimelineRouteImport.update({
    id: '/fixtures/$fixtureId_/timeline',
    path: '/fixtures/$fixtureId/timeline',
    getParentRoute: () => rootRouteImport,
  } as any)
const TeamsTeamIdSquadRoute = TeamsTeamIdSquadRouteImport.update({
  id: '/teams_/$teamId_/squad',
  path: '/teams/$teamId/squad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/settings': typeof SettingsRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/fixtures/$fixtureId/lineups': typeof FixturesFixtureIdLineupsRoute
  '/fixtures/$fixtureId/odds': typeof FixturesFixtureIdOddsRoute
  '/fixtures/$fixtureId/stats': typeof FixturesFixtureIdStatsRoute
  '/fixtures/$fixtureId/timeline': typeof FixturesFixtureIdTimelineRoute
  '/teams/$teamId/squad': typeof TeamsTeamIdSquadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/settings': typeof SettingsRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/fixtures/$fixtureId/lineups': typeof FixturesFixtureIdLineupsRoute
  '/fixtures/$fixtureId/odds': typeof FixturesFixtureIdOddsRoute
  '/fixtures/$fixtureId/stats': typeof FixturesFixtureIdStatsRoute
  '/fixtures/$fixtureId/timeline': typeof FixturesFixtureIdTimelineRoute
  '/teams/$teamId/squad': typeof TeamsTeamIdSquadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/settings': typeof SettingsRoute
  '/competitions_/$competitionId': typeof CompetitionsCompetitionIdRoute
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRoute
  '/players_/$playerId': typeof PlayersPlayerIdRoute
  '/teams_/$teamId': typeof TeamsTeamIdRoute
  '/venues_/$venueId': typeof VenuesVenueIdRoute
  '/fixtures/$fixtureId_/lineups': typeof FixturesFixtureIdLineupsRoute
  '/fixtures/$fixtureId_/odds': typeof FixturesFixtureIdOddsRoute
  '/fixtures/$fixtureId_/stats': typeof FixturesFixtureIdStatsRoute
  '/fixtures/$fixtureId_/timeline': typeof FixturesFixtureIdTimelineRoute
  '/teams_/$teamId_/squad': typeof TeamsTeamIdSquadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitions'
    | '/settings'
    | '/competitions/$competitionId'
    | '/fixtures/$fixtureId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/venues/$venueId'
    | '/fixtures/$fixtureId/lineups'
    | '/fixtures/$fixtureId/odds'
    | '/fixtures/$fixtureId/stats'
    | '/fixtures/$fixtureId/timeline'
    | '/teams/$teamId/squad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitions'
    | '/settings'
    | '/competitions/$competitionId'
    | '/fixtures/$fixtureId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/venues/$venueId'
    | '/fixtures/$fixtureId/lineups'
    | '/fixtures/$fixtureId/odds'
    | '/fixtures/$fixtureId/stats'
    | '/fixtures/$fixtureId/timeline'
    | '/teams/$teamId/squad'
  id:
    | '__root__'
    | '/'
    | '/competitions'
    | '/settings'
    | '/competitions_/$competitionId'
    | '/fixtures/$fixtureId'
    | '/players_/$playerId'
    | '/teams_/$teamId'
    | '/venues_/$venueId'
    | '/fixtures/$fixtureId_/lineups'
    | '/fixtures/$fixtureId_/odds'
    | '/fixtures/$fixtureId_/stats'
    | '/fixtures/$fixtureId_/timeline'
    | '/teams_/$teamId_/squad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsRoute: typeof CompetitionsRoute
  SettingsRoute: typeof SettingsRoute
  CompetitionsCompetitionIdRoute: typeof CompetitionsCompetitionIdRoute
  FixturesFixtureIdRoute: typeof FixturesFixtureIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
  FixturesFixtureIdLineupsRoute: typeof FixturesFixtureIdLineupsRoute
  FixturesFixtureIdOddsRoute: typeof FixturesFixtureIdOddsRoute
  FixturesFixtureIdStatsRoute: typeof FixturesFixtureIdStatsRoute
  FixturesFixtureIdTimelineRoute: typeof FixturesFixtureIdTimelineRoute
  TeamsTeamIdSquadRoute: typeof TeamsTeamIdSquadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions_/$competitionId': {
      id: '/competitions_/$competitionId'
      path: '/competitions/$competitionId'
      fullPath: '/competitions/$competitionId'
      preLoaderRoute: typeof CompetitionsCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId': {
      id: '/fixtures/$fixtureId'
      path: '/fixtures/$fixtureId'
      fullPath: '/fixtures/$fixtureId'
      preLoaderRoute: typeof FixturesFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players_/$playerId': {
      id: '/players_/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams_/$teamId': {
      id: '/teams_/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues_/$venueId': {
      id: '/venues_/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId_/lineups': {
      id: '/fixtures/$fixtureId_/lineups'
      path: '/fixtures/$fixtureId/lineups'
      fullPath: '/fixtures/$fixtureId/lineups'
      preLoaderRoute: typeof FixturesFixtureIdLineupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId_/odds': {
      id: '/fixtures/$fixtureId_/odds'
      path: '/fixtures/$fixtureId/odds'
      fullPath: '/fixtures/$fixtureId/odds'
      preLoaderRoute: typeof FixturesFixtureIdOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId_/stats': {
      id: '/fixtures/$fixtureId_/stats'
      path: '/fixtures/$fixtureId/stats'
      fullPath: '/fixtures/$fixtureId/stats'
      preLoaderRoute: typeof FixturesFixtureIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId_/timeline': {
      id: '/fixtures/$fixtureId_/timeline'
      path: '/fixtures/$fixtureId/timeline'
      fullPath: '/fixtures/$fixtureId/timeline'
      preLoaderRoute: typeof FixturesFixtureIdTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams_/$teamId_/squad': {
      id: '/teams_/$teamId_/squad'
      path: '/teams/$teamId/squad'
      fullPath: '/teams/$teamId/squad'
      preLoaderRoute: typeof TeamsTeamIdSquadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsRoute: CompetitionsRoute,
  SettingsRoute: SettingsRoute,
  CompetitionsCompetitionIdRoute: CompetitionsCompetitionIdRoute,
  FixturesFixtureIdRoute: FixturesFixtureIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  VenuesVenueIdRoute: VenuesVenueIdRoute,
  FixturesFixtureIdLineupsRoute: FixturesFixtureIdLineupsRoute,
  FixturesFixtureIdOddsRoute: FixturesFixtureIdOddsRoute,
  FixturesFixtureIdStatsRoute: FixturesFixtureIdStatsRoute,
  FixturesFixtureIdTimelineRoute: FixturesFixtureIdTimelineRoute,
  TeamsTeamIdSquadRoute: TeamsTeamIdSquadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
