/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CompetitionsCompetitionIdRouteImport } from './routes/competitions_.$competitionId'
import { Route as FixturesFixtureIdRouteImport } from './routes/fixtures.$fixtureId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players_.$playerId'
import { Route as TeamsTeamIdRouteImport } from './routes/teams_.$teamId'
import { Route as VenuesVenueIdRouteImport } from './routes/venues_.$venueId'
import { Route as CompetitionsCompetitionIdFixturesRouteImport } from './routes/competitions_.$competitionId.fixtures'
import { Route as CompetitionsCompetitionIdTeamsRouteImport } from './routes/competitions_.$competitionId.teams'
import { Route as FixturesFixtureIdLineupsRouteImport } from './routes/fixtures.$fixtureId.lineups'
import { Route as FixturesFixtureIdOddsRouteImport } from './routes/fixtures.$fixtureId.odds'
import { Route as FixturesFixtureIdStatsRouteImport } from './routes/fixtures.$fixtureId.stats'
import { Route as FixturesFixtureIdTimelineRouteImport } from './routes/fixtures.$fixtureId.timeline'
import { Route as TeamsTeamIdSquadRouteImport } from './routes/teams_.$teamId.squad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsCompetitionIdRoute =
  CompetitionsCompetitionIdRouteImport.update({
    id: '/competitions_/$competitionId',
    path: '/competitions/$competitionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const FixturesFixtureIdRoute = FixturesFixtureIdRouteImport.update({
  id: '/fixtures/$fixtureId',
  path: '/fixtures/$fixtureId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players_/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams_/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesVenueIdRoute = VenuesVenueIdRouteImport.update({
  id: '/venues_/$venueId',
  path: '/venues/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsCompetitionIdFixturesRoute =
  CompetitionsCompetitionIdFixturesRouteImport.update({
    id: '/fixtures',
    path: '/fixtures',
    getParentRoute: () => CompetitionsCompetitionIdRoute,
  } as any)
const CompetitionsCompetitionIdTeamsRoute =
  CompetitionsCompetitionIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => CompetitionsCompetitionIdRoute,
  } as any)
const FixturesFixtureIdLineupsRoute =
  FixturesFixtureIdLineupsRouteImport.update({
    id: '/lineups',
    path: '/lineups',
    getParentRoute: () => FixturesFixtureIdRoute,
  } as any)
const FixturesFixtureIdOddsRoute = FixturesFixtureIdOddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => FixturesFixtureIdRoute,
} as any)
const FixturesFixtureIdStatsRoute = FixturesFixtureIdStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => FixturesFixtureIdRoute,
} as any)
const FixturesFixtureIdTimelineRoute =
  FixturesFixtureIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => FixturesFixtureIdRoute,
  } as any)
const TeamsTeamIdSquadRoute = TeamsTeamIdSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => TeamsTeamIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/settings': typeof SettingsRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRouteWithChildren
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRouteWithChildren
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/competitions/$competitionId/fixtures': typeof CompetitionsCompetitionIdFixturesRoute
  '/competitions/$competitionId/teams': typeof CompetitionsCompetitionIdTeamsRoute
  '/fixtures/$fixtureId/lineups': typeof FixturesFixtureIdLineupsRoute
  '/fixtures/$fixtureId/odds': typeof FixturesFixtureIdOddsRoute
  '/fixtures/$fixtureId/stats': typeof FixturesFixtureIdStatsRoute
  '/fixtures/$fixtureId/timeline': typeof FixturesFixtureIdTimelineRoute
  '/teams/$teamId/squad': typeof TeamsTeamIdSquadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/settings': typeof SettingsRoute
  '/competitions/$competitionId': typeof CompetitionsCompetitionIdRouteWithChildren
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRouteWithChildren
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/venues/$venueId': typeof VenuesVenueIdRoute
  '/competitions/$competitionId/fixtures': typeof CompetitionsCompetitionIdFixturesRoute
  '/competitions/$competitionId/teams': typeof CompetitionsCompetitionIdTeamsRoute
  '/fixtures/$fixtureId/lineups': typeof FixturesFixtureIdLineupsRoute
  '/fixtures/$fixtureId/odds': typeof FixturesFixtureIdOddsRoute
  '/fixtures/$fixtureId/stats': typeof FixturesFixtureIdStatsRoute
  '/fixtures/$fixtureId/timeline': typeof FixturesFixtureIdTimelineRoute
  '/teams/$teamId/squad': typeof TeamsTeamIdSquadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/competitions': typeof CompetitionsRoute
  '/settings': typeof SettingsRoute
  '/competitions_/$competitionId': typeof CompetitionsCompetitionIdRouteWithChildren
  '/fixtures/$fixtureId': typeof FixturesFixtureIdRouteWithChildren
  '/players_/$playerId': typeof PlayersPlayerIdRoute
  '/teams_/$teamId': typeof TeamsTeamIdRouteWithChildren
  '/venues_/$venueId': typeof VenuesVenueIdRoute
  '/competitions_/$competitionId/fixtures': typeof CompetitionsCompetitionIdFixturesRoute
  '/competitions_/$competitionId/teams': typeof CompetitionsCompetitionIdTeamsRoute
  '/fixtures/$fixtureId/lineups': typeof FixturesFixtureIdLineupsRoute
  '/fixtures/$fixtureId/odds': typeof FixturesFixtureIdOddsRoute
  '/fixtures/$fixtureId/stats': typeof FixturesFixtureIdStatsRoute
  '/fixtures/$fixtureId/timeline': typeof FixturesFixtureIdTimelineRoute
  '/teams_/$teamId/squad': typeof TeamsTeamIdSquadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/competitions'
    | '/settings'
    | '/competitions/$competitionId'
    | '/fixtures/$fixtureId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/venues/$venueId'
    | '/competitions/$competitionId/fixtures'
    | '/competitions/$competitionId/teams'
    | '/fixtures/$fixtureId/lineups'
    | '/fixtures/$fixtureId/odds'
    | '/fixtures/$fixtureId/stats'
    | '/fixtures/$fixtureId/timeline'
    | '/teams/$teamId/squad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/competitions'
    | '/settings'
    | '/competitions/$competitionId'
    | '/fixtures/$fixtureId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/venues/$venueId'
    | '/competitions/$competitionId/fixtures'
    | '/competitions/$competitionId/teams'
    | '/fixtures/$fixtureId/lineups'
    | '/fixtures/$fixtureId/odds'
    | '/fixtures/$fixtureId/stats'
    | '/fixtures/$fixtureId/timeline'
    | '/teams/$teamId/squad'
  id:
    | '__root__'
    | '/'
    | '/competitions'
    | '/settings'
    | '/competitions_/$competitionId'
    | '/fixtures/$fixtureId'
    | '/players_/$playerId'
    | '/teams_/$teamId'
    | '/venues_/$venueId'
    | '/competitions_/$competitionId/fixtures'
    | '/competitions_/$competitionId/teams'
    | '/fixtures/$fixtureId/lineups'
    | '/fixtures/$fixtureId/odds'
    | '/fixtures/$fixtureId/stats'
    | '/fixtures/$fixtureId/timeline'
    | '/teams_/$teamId/squad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompetitionsRoute: typeof CompetitionsRoute
  SettingsRoute: typeof SettingsRoute
  CompetitionsCompetitionIdRoute: typeof CompetitionsCompetitionIdRouteWithChildren
  FixturesFixtureIdRoute: typeof FixturesFixtureIdRouteWithChildren
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRouteWithChildren
  VenuesVenueIdRoute: typeof VenuesVenueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions_/$competitionId': {
      id: '/competitions_/$competitionId'
      path: '/competitions/$competitionId'
      fullPath: '/competitions/$competitionId'
      preLoaderRoute: typeof CompetitionsCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures/$fixtureId': {
      id: '/fixtures/$fixtureId'
      path: '/fixtures/$fixtureId'
      fullPath: '/fixtures/$fixtureId'
      preLoaderRoute: typeof FixturesFixtureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players_/$playerId': {
      id: '/players_/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams_/$teamId': {
      id: '/teams_/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues_/$venueId': {
      id: '/venues_/$venueId'
      path: '/venues/$venueId'
      fullPath: '/venues/$venueId'
      preLoaderRoute: typeof VenuesVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions_/$competitionId/fixtures': {
      id: '/competitions_/$competitionId/fixtures'
      path: '/fixtures'
      fullPath: '/competitions/$competitionId/fixtures'
      preLoaderRoute: typeof CompetitionsCompetitionIdFixturesRouteImport
      parentRoute: typeof CompetitionsCompetitionIdRoute
    }
    '/competitions_/$competitionId/teams': {
      id: '/competitions_/$competitionId/teams'
      path: '/teams'
      fullPath: '/competitions/$competitionId/teams'
      preLoaderRoute: typeof CompetitionsCompetitionIdTeamsRouteImport
      parentRoute: typeof CompetitionsCompetitionIdRoute
    }
    '/fixtures/$fixtureId/lineups': {
      id: '/fixtures/$fixtureId/lineups'
      path: '/lineups'
      fullPath: '/fixtures/$fixtureId/lineups'
      preLoaderRoute: typeof FixturesFixtureIdLineupsRouteImport
      parentRoute: typeof FixturesFixtureIdRoute
    }
    '/fixtures/$fixtureId/odds': {
      id: '/fixtures/$fixtureId/odds'
      path: '/odds'
      fullPath: '/fixtures/$fixtureId/odds'
      preLoaderRoute: typeof FixturesFixtureIdOddsRouteImport
      parentRoute: typeof FixturesFixtureIdRoute
    }
    '/fixtures/$fixtureId/stats': {
      id: '/fixtures/$fixtureId/stats'
      path: '/stats'
      fullPath: '/fixtures/$fixtureId/stats'
      preLoaderRoute: typeof FixturesFixtureIdStatsRouteImport
      parentRoute: typeof FixturesFixtureIdRoute
    }
    '/fixtures/$fixtureId/timeline': {
      id: '/fixtures/$fixtureId/timeline'
      path: '/timeline'
      fullPath: '/fixtures/$fixtureId/timeline'
      preLoaderRoute: typeof FixturesFixtureIdTimelineRouteImport
      parentRoute: typeof FixturesFixtureIdRoute
    }
    '/teams_/$teamId/squad': {
      id: '/teams_/$teamId/squad'
      path: '/squad'
      fullPath: '/teams/$teamId/squad'
      preLoaderRoute: typeof TeamsTeamIdSquadRouteImport
      parentRoute: typeof TeamsTeamIdRoute
    }
  }
}

interface CompetitionsCompetitionIdRouteChildren {
  CompetitionsCompetitionIdFixturesRoute: typeof CompetitionsCompetitionIdFixturesRoute
  CompetitionsCompetitionIdTeamsRoute: typeof CompetitionsCompetitionIdTeamsRoute
}

const CompetitionsCompetitionIdRouteChildren: CompetitionsCompetitionIdRouteChildren =
  {
    CompetitionsCompetitionIdFixturesRoute:
      CompetitionsCompetitionIdFixturesRoute,
    CompetitionsCompetitionIdTeamsRoute: CompetitionsCompetitionIdTeamsRoute,
  }

const CompetitionsCompetitionIdRouteWithChildren =
  CompetitionsCompetitionIdRoute._addFileChildren(
    CompetitionsCompetitionIdRouteChildren,
  )

interface FixturesFixtureIdRouteChildren {
  FixturesFixtureIdLineupsRoute: typeof FixturesFixtureIdLineupsRoute
  FixturesFixtureIdOddsRoute: typeof FixturesFixtureIdOddsRoute
  FixturesFixtureIdStatsRoute: typeof FixturesFixtureIdStatsRoute
  FixturesFixtureIdTimelineRoute: typeof FixturesFixtureIdTimelineRoute
}

const FixturesFixtureIdRouteChildren: FixturesFixtureIdRouteChildren = {
  FixturesFixtureIdLineupsRoute: FixturesFixtureIdLineupsRoute,
  FixturesFixtureIdOddsRoute: FixturesFixtureIdOddsRoute,
  FixturesFixtureIdStatsRoute: FixturesFixtureIdStatsRoute,
  FixturesFixtureIdTimelineRoute: FixturesFixtureIdTimelineRoute,
}

const FixturesFixtureIdRouteWithChildren =
  FixturesFixtureIdRoute._addFileChildren(FixturesFixtureIdRouteChildren)

interface TeamsTeamIdRouteChildren {
  TeamsTeamIdSquadRoute: typeof TeamsTeamIdSquadRoute
}

const TeamsTeamIdRouteChildren: TeamsTeamIdRouteChildren = {
  TeamsTeamIdSquadRoute: TeamsTeamIdSquadRoute,
}

const TeamsTeamIdRouteWithChildren = TeamsTeamIdRoute._addFileChildren(
  TeamsTeamIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompetitionsRoute: CompetitionsRoute,
  SettingsRoute: SettingsRoute,
  CompetitionsCompetitionIdRoute: CompetitionsCompetitionIdRouteWithChildren,
  FixturesFixtureIdRoute: FixturesFixtureIdRouteWithChildren,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRouteWithChildren,
  VenuesVenueIdRoute: VenuesVenueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
